import { diff } from "./services/Difficulty.js"
import { dom } from "./services/dom.js"
import { GameState } from "./services/GameState.js"
import { GameService } from "./services/GameLogic.js"
import { Question } from "./services/Question.js"